name: ros2-talker-listener
base: core20
version: '0.1'
summary: ROS2 Talker/Listener Launch Example
grade: devel
confinement: strict
description: |
  This example launches a ROS2 talker and listener.

parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/ros2/demos.git
    source-branch: foxy
    source-subdir: demo_nodes_cpp
    build-packages: [make, gcc, g++] # packages required for the part to build
    stage-packages: [ros-foxy-ros2launch] # packages required to run the part

apps:
  ros2-talker-listener:
    command: opt/ros/foxy/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
    plugs: [network, network-bind]
    extensions: [ros2-foxy]
