name: ros2-talker
base: core20
version: '0.1'
summary: ROS2 Talker Executableh Example
grade: devel
confinement: strict
description: |
  This example launches a ROS2 talker.

parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/ros2/demos.git
    source-branch: foxy
    source-subdir: demo_nodes_cpp
    build-packages: [make, gcc, g++] # packages required for the part to build
    stage-packages: [ros-foxy-ros2launch, ros-foxy-ros2cli, ros-foxy-ros2run] # packages required to run the part

apps:
  ros2-talker:
    command: opt/ros/foxy/bin/ros2 run demo_nodes_cpp talker
    plugs: [network, network-bind]
    extensions: [ros2-foxy]
